name: Frontend Cypress E2E Test

on:
  pull_request:
    branches:
      - develop-cypress
    paths:
      - frontend/**
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend

permissions:
  checks: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v3

      - name : Set up Node 18.16.0 
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          
      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: | 
            ${{ runner.os }}-node-
          
      - name: Install dependencies
        run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          working-directory: frontend
          start: npm run start
